### ISSUE TITLE
Sending traces produces new traces which are again sent to AppInsights

### ISSUE THREAD

**Issue by RumataEstor** [frigus02/opentelemetry-application-insights#35]
Thanks for the library, with it I have a chance of using Rust at work as one of the requirements for using a new language in it is having application insights integration.

We have implemented a small webserver using warp and wanted to forward its traces to Application Insights using opentelemetry and this library. Integration worked quite well at the first glance, but later I noticed unexpected traces named `parse_headers` and `encode_headers` targetting `hyper::proto::h1::role`.

As we use `reqwest` which also depends on `hyper`, I tried to ensure it's not our usage of that what produce those unexpected traces. So I took the https://github.com/frigus02/opentelemetry-application-insights/blob/main/examples/tracing/src/main.rs and applied 2 changes: 

```rust
    let tracer =
        opentelemetry_application_insights::new_pipeline(instrumentation_key)
            .with_client(reqwest::Client::new())
            .install_batch(opentelemetry::runtime::Tokio); // replaced .install()
```

and

```rust
    tokio::time::sleep(Duration::from_secs(10)).await;
    opentelemetry::global::shutdown_tracer_provider();
    Ok(())
} // fn main
```

so the application runs a little longer after the normal work is done and that resulted in a lot of the same additional traces
![image](https://user-images.githubusercontent.com/200992/118421139-d74f1080-b703-11eb-9af6-3f63d4b2353d.png)

For now I solved that problem by adding a tracing filter which discards `hyper::proto::h1::role` traces however I noticed that our usage of `reqwest` didn't result in such traces added and those were only produced by tracing.

I thought there might be some configuration option or method to stop those traces from being produced. Is there one or filtering is the only option?

**Comment by frigus02** [comment]
Hi. Sorry for the late reply. I had a quick look at `hyper`. Looks like it's using `trace_span` to expose debug information ([code](https://github.com/hyperium/hyper/blob/dbea7716f157896bf7d2d417be7b4e382e7dc34f/src/proto/h1/role.rs#L96)). This is likely a bit much for a normal application. And it's very unfortunate that this is then even logged for requests done from the exporter.

I'm not aware of a perfect solution. Instead of filtering "hyper::proto::h1::role" traces, maybe you could filter for the trace level and discard `TRACE` and maybe `DEBUG` traces.

This could also be something to ask for in [`tracing`](https://github.com/tokio-rs/tracing) directly. I feel like we can't be the only ones with this issue.

**Comment by frigus02** [comment]
Closing this for now, because I don't think we can do a whole lot about it here. Feel free to reopen if you have further questions, though.

**Comment by Dessix** [comment]
@frigus02 now that `tracing_subscriber` has reached 0.3.1, it has dynamic filter modules built in. Would you be open to accepting a PR which suggests a filter for `hyper`-originated traces in the readme?

**Comment by frigus02** [comment]
Yes, absolutely. I imagine more people may run into the same issue. It sounds useful to have a solution for it in the readme.
