### ISSUE TITLE
`tracing` example does not seems register calls

### ISSUE THREAD

**Issue by johnchildren** [frigus02/opentelemetry-application-insights#5]
When running the `tracing` example I'm not seeing any calls being registered in application insights, however the `opentelemetry` example seems to work as expected. Strangely the component for `tracing` is being registered in the application map at least. I have attached two images to demonstrate the issue, I ran the `tracing` example a few times and the `opentelemetry` one twice.

![image](https://user-images.githubusercontent.com/32305209/89038318-07c1eb80-d338-11ea-86ae-b6d4ab2d7882.png)

![image](https://user-images.githubusercontent.com/32305209/89038348-15777100-d338-11ea-8312-e07df641b79b.png)

I would be interested in investigating this issue and contributing a patch if it is unexpected behavior, but would appreciate some pointers if anyone has ideas on where to start investigating.

EDIT: diving into this a bit, it seems that the difference is that none of the Envelopes uploaded are named `Microsoft.ApplicationInsights.Request` as they are not of the right SpanKind. Would it be worth also demonstrating setting the SpanKind in the tracing example or should I close this issue?

**Comment by johnchildren** [comment]
Reading through the documentation again and looking at the code I'm reasonably convinced now that this is due to limitations with `tracing-opentelemetry`, as I would like to be able to set the SpanKind for my `tracing` spans but can't see an obvious way to do that, will pursue this further there.

**Comment by frigus02** [comment]
Yeah, specifying a SpanKind is not supported by `tracing-opentelemetry`, unfortunately. I think I would be happy to add a workaround here.

We could support an attribute `span.kind` and make it so that `tracing::info_span!("child", span.kind = "server")` sends request telemetry.

Although the better solution is probably to add support for SpanKind in `tracing-opentelemetry`. I see it already supports a special attribute `otel.name`. So it might be doable to support something like `otel.spankind`.

**Comment by johnchildren** [comment]
https://github.com/tokio-rs/tracing/issues/747 looks there might be something in the works for this

**Comment by frigus02** [comment]
The `span.kind` attribute is just passed through as the moment. It's not translated to a SpanKind. The Zipkin and Jaeger exporters in [open-telemetry/opentelemetry-rust](https://github.com/open-telemetry/opentelemetry-rust) both seem to respect that attribute and prefer it over the SpanKind property.

I wonder if that's what we should do here, too 🤔

**Comment by jtescher** [comment]
Hey all 👋  yeah we just pass through for now as that seems to be least confusing for people who are specifying that way. I've opened a spec issue to address the ambiguity here https://github.com/open-telemetry/opentelemetry-specification/issues/660 so there may be a change in this behavior of some attributes become reserved.

**Comment by frigus02** [comment]
Hi @jtescher, thanks for dropping by. The problem here is that Azure Application Insights needs entirely different models for `client` and for `server` spans. In order to use features that rely on this distinction with the `tracing` crate, we would need some way of figuring out the span kind.

Do you think it makes sense to add support in [tracing-opentelemetry](https://docs.rs/tracing-opentelemetry) to properly set the span kind (possibly similar to how `otel.name` works for the span name)? Or does it make more sense to leave this up to the exporters?

**Comment by jtescher** [comment]
Yeah I think having the span kind set from `otel.kind` or something similar would make sense in `tracing-opentelemetry`. Want to open a PR or issue to that effect?

**Comment by frigus02** [comment]
Sounds good. I'll try to open a PR.

**Comment by frigus02** [comment]
@johnchildren `opentelemetry-tracing` 0.7.0 is out, which supports the `otel.kind` attribute. I updated the tracing example and it now shows the application map in the same way as the pure opentelemetry one does.

**Comment by johnchildren** [comment]
Fantastic, thanks for letting me know! Will try this out as soon as I can.
