### ISSUE TITLE
Resource attributes in events

### ISSUE THREAD

**Issue by kmotyka-zx** [frigus02/opentelemetry-application-insights#67]
Hi, I'm currently trying to setup AppIns in my service and in particular I'd like to set properties such as `cloud_RoleName` or `cloud_RoleInstance`. After reading docs I've managed to add following configuration part
```
let tracer = opentelemetry_application_insights::new_pipeline_from_connection_string(
    "..."
)
...
.with_trace_config(opentelemetry_sdk::trace::config().with_resource(
    opentelemetry_sdk::Resource::new(vec![
        opentelemetry::KeyValue::new("service.namespace", "namespace"),
        opentelemetry::KeyValue::new("service.version", "version"),
        opentelemetry::KeyValue::new("service.name", "name"),
        opentelemetry::KeyValue::new("service.instance.id", "id"),
    ]),
))
```
and it correctly maps to respective AppIns fields for spans (dependencies). However, they don't appear for events (traces). I've tried also setting directly `ai.*` attributes but this didn't help either. Now, is it desired behavior or am I missing something?

**Comment by frigus02** [comment]
Yeah, you're right.  Events don't currently include resource attributes.

Honestly, I don't know if this was deliberate. Maybe I assumed they aren't necessary because an event is assoiated with a span and App Insights can infer them from there. Or maybe I didn't think about anything.

I assume you're seeing issues because the events don't include cloud rolename/roleinstance?

**Comment by frigus02** [comment]
Looking at the JavaScript exporter, they also differentiate tags for spans and events. But events do get some more tags than they do with this crate. So that's definitely a bug.

- Currently this crate only adds 2 tags (operationId and operationParentId): https://github.com/frigus02/opentelemetry-application-insights/blob/73b266ca6eea29ccfb6d3992d1b7a05f5490c5d2/src/tags.rs#L53-L61
- The JS exporter adds those additional tags: https://github.com/Azure/azure-sdk-for-js/blob/9646e4e3e438fe3a07325989830dd6be35cefc23/sdk/monitor/monitor-opentelemetry-exporter/src/utils/common.ts#L52-L73

**Comment by frigus02** [comment]
#68 fixes that. This crate still doesn't extract the same tags as the JS exporter does, but at least this makes tag extraction consistent between spans and events and extracts rolename and roleinstance for events.

#68 would also be a breaking change for spans. I don't think it should affect a lot of people. I assume most users specify the cloud role/instance in the resource attributes. I'm going to sleep over this and will try to release the fix over the next few days.

**Comment by kmotyka-zx** [comment]
> I assume you're seeing issues because the events don't include cloud rolename/roleinstance?

Exactly. 

> (...) an event is assoiated with a span and App Insights can infer them from there.

I did some digging and found that in "transaction search" view those events are reachable through their parent spans, you meant that? Maybe I need to change my assumptions about how to query this tracing data because currently in my workplace, which uses dotnet, the logging framework emits those attributes for AppIns `traces` so it is very easy to quickly filter those in the "logs" view.

**Comment by frigus02** [comment]
All done. Pushed version 0.31.0, which currently sets cloud role, cloud instance, etc for events.

Thanks for reporting. Also, please let me know if this still doesn't work as expected for some reason.

**Comment by kmotyka-zx** [comment]
Thank you! It seems it works just fine with the new version.
